//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevelopUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevelopUser()
        {
            this.DevelopPowerFuns = new HashSet<DevelopPowerFun>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public decimal DevelopAge { get; set; }
        public string Pwd { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevelopPowerFun> DevelopPowerFuns { get; set; }
    }
}
